# Generated by Django 4.2.4 on 2023-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoCalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ManyToManyField(to='TodoCalendarApp.user'),
        ),
    ]
